2018-01-09 17:10:07.708 [error] <0.439.0> CRASH REPORT Process <0.439.0> with 0 neighbours exited with reason: {unexpected_message,"login fail"} in gb_reader:login_lost/4 line 265
2018-01-09 17:10:07.708 [error] <0.135.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.439.0> exit with reason {unexpected_message,"login fail"} in context child_terminated
2018-01-09 17:12:07.603 [error] <0.571.0> CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: {unexpected_message,"register fail"} in gb_reader:login_lost/4 line 265
2018-01-09 17:12:07.603 [error] <0.135.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.571.0> exit with reason {unexpected_message,"register fail"} in context child_terminated
2018-01-09 17:12:48.478 [error] <0.776.0> CRASH REPORT Process <0.776.0> with 0 neighbours exited with reason: {unexpected_message,"login fail"} in gb_reader:login_lost/4 line 265
2018-01-09 17:12:48.478 [error] <0.135.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.776.0> exit with reason {unexpected_message,"login fail"} in context child_terminated
2018-01-09 17:13:54.424 [error] <0.843.0>@gen_server:call CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(mod_id, {generate,role}) in gen_server:call/2 line 204
2018-01-09 17:13:54.425 [error] <0.135.0>@gen_server:call Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.843.0> exit with reason no such process or port in call to gen_server:call(mod_id, {generate,role}) in context child_terminated
2018-01-09 17:16:43.378 [error] <0.91.0>@gen_server:call CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(mod_id, {start_child,{mod_id,{mod_id,start_link,[]},permanent,10000,supervisor,[mod_id]}}, infinity) in application_master:init/4 line 134
2018-01-09 17:17:15.112 [error] <0.91.0>@gen_server:call CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(mod_id, {start_child,{mod_id,{mod_id,start_link,[]},permanent,10000,supervisor,[mod_id]}}, infinity) in application_master:init/4 line 134
2018-01-09 17:17:55.854 [error] <0.135.0>@db_util:do:56 CRASH REPORT Process <0.135.0> with 0 neighbours exited with reason: no match of right hand value {aborted,{{case_clause,1},[{db_util,'-get_max_role_id/0-fun-1-',7,[{file,"src/DB/db_util.erl"},{line,34}]},{qlc,collect,1,[{file,"qlc.erl"},{line,1342}]},{qlc,eval,2,[{file,"qlc.erl"},{line,299}]},{mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,836}]},{mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,811}]},{db_util,do,1,[{file,"src/DB/db_util.erl"},{line,56}]},{mod_id,init,1,[{file,"src/mod/mod_id.erl"},{line,28}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}} in db_util:do/1 line 56 in gen_server:init_it/6 line 352
2018-01-09 17:17:55.854 [error] <0.91.0>@gb_network:start_id:63 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{{badmatch,{aborted,{{case_clause,1},[{db_util,'-get_max_role_id/0-fun-1-',7,[{file,"src/DB/db_util.erl"},{line,34}]},{qlc,collect,1,[{file,"qlc.erl"},{line,1342}]},{qlc,eval,2,[{file,"qlc.erl"},{line,299}]},{mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,836}]},{mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,811}]},{db_util,do,1,[{file,"src/DB/db_util.erl"},{line,56}]},{mod_id,init,1,[{file,"src/mod/mod_id.erl"},{line,28}]},{gen_server,init_it,6,[{file,"gen_se..."},...]}]}}},...},...}} in gb_network:start_id/0 line 63 in application_master:init/4 line 134
2018-01-09 17:34:07.677 [error] <0.151.0>@proto_util:name_to_id CRASH REPORT Process <0.151.0> with 0 neighbours crashed with reason: call to undefined function proto_util:name_to_id(s2c_login_reply, 0)
2018-01-09 17:34:07.677 [error] <0.137.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.151.0> exit with reason undef in context child_terminated
2018-01-09 17:34:17.436 [error] <0.153.0>@proto_util:name_to_id CRASH REPORT Process <0.153.0> with 0 neighbours crashed with reason: call to undefined function proto_util:name_to_id(s2c_login_reply, 1)
2018-01-09 17:34:17.436 [error] <0.137.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.153.0> exit with reason undef in context child_terminated
2018-01-09 17:35:59.667 [error] <0.118.0>@db_util:do:55 CRASH REPORT Process <0.118.0> with 0 neighbours exited with reason: no match of right hand value {aborted,{no_exists,{account,disc_copies}}} in db_util:do/1 line 55 in gen_server:init_it/6 line 352
2018-01-09 17:35:59.667 [error] <0.97.0>@gb_network:start_id:63 CRASH REPORT Process <0.97.0> with 0 neighbours exited with reason: no match of right hand value {error,{{{badmatch,{aborted,{no_exists,{account,disc_copies}}}},[{db_util,do,1,[{file,"src/DB/db_util.erl"},{line,55}]},{mod_id,init,1,[{file,"src/mod/mod_id.erl"},{line,28}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_id,{mod_id,start_link,[]},permanent,10000,supervisor,[mod_id]}}} in gb_network:start_id/0 line 63 in application_master:init/4 line 134
2018-01-09 17:36:27.902 [error] <0.151.0>@gb_reader:login_parse_packet:84 CRASH REPORT Process <0.151.0> with 0 neighbours crashed with reason: no match of right hand value {ok,<<6,0,18,39,0,0,8,1>>} in gb_reader:login_parse_packet/2 line 84
2018-01-09 17:36:27.903 [error] <0.137.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.151.0> exit with reason {badmatch,{ok,<<6,0,18,39,0,0,8,1>>}} in context child_terminated
2018-01-09 17:53:32.050 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {unexpected_message,"login fail"} in gb_reader:login_lost/4 line 269
2018-01-09 17:53:32.050 [error] <0.137.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.156.0> exit with reason {unexpected_message,"login fail"} in context child_terminated
2018-01-09 18:12:58.078 [error] <0.151.0>@pt_10:write:60 CRASH REPORT Process <0.151.0> with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_list([[["\b",[1]]]]) in pt_10:write/2 line 60
2018-01-09 18:12:58.079 [error] <0.137.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.151.0> exit with reason badarg in context child_terminated
2018-01-09 20:27:45.369 [error] emulator Bad value on output port 'tcp_inet'

2018-01-09 20:31:10.709 [error] <0.135.0>@db_util:do:55 CRASH REPORT Process <0.135.0> with 0 neighbours exited with reason: no match of right hand value {aborted,{no_exists,account}} in db_util:do/1 line 55 in gen_server:init_it/6 line 352
2018-01-09 20:32:13.734 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {unexpected_message,"register fail"} in gb_reader:login_lost/4 line 273
2018-01-09 20:32:13.735 [error] <0.137.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.151.0> exit with reason {unexpected_message,"register fail"} in context child_terminated
2018-01-09 20:37:51.655 [error] <0.139.0>@db_util:do:55 CRASH REPORT Process <0.139.0> with 0 neighbours exited with reason: no match of right hand value {aborted,{no_exists,account}} in db_util:do/1 line 55 in gen_server:init_it/6 line 352
2018-01-09 20:37:51.655 [error] <0.91.0>@gb_network:start_id:63 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{{badmatch,{aborted,{no_exists,account}}},[{db_util,do,1,[{file,"src/DB/db_util.erl"},{line,55}]},{mod_id,init,1,[{file,"src/mod/mod_id.erl"},{line,28}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_id,{mod_id,start_link,[]},permanent,10000,supervisor,[mod_id]}}} in gb_network:start_id/0 line 63 in application_master:init/4 line 134
2018-01-09 20:44:53.400 [error] <0.140.0>@db_util:do:55 CRASH REPORT Process <0.140.0> with 0 neighbours exited with reason: no match of right hand value {aborted,{no_exists,account}} in db_util:do/1 line 55 in gen_server:init_it/6 line 352
2018-01-09 20:44:53.400 [error] <0.91.0>@gb_network:start_id:63 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{{badmatch,{aborted,{no_exists,account}}},[{db_util,do,1,[{file,"src/DB/db_util.erl"},{line,55}]},{mod_id,init,1,[{file,"src/mod/mod_id.erl"},{line,28}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_id,{mod_id,start_link,[]},permanent,10000,supervisor,[mod_id]}}} in gb_network:start_id/0 line 63 in application_master:init/4 line 134
2018-01-09 20:51:18.273 [error] <0.143.0>@db_util:do:57 CRASH REPORT Process <0.143.0> with 0 neighbours exited with reason: no match of right hand value {aborted,{no_exists,account}} in db_util:do/1 line 57 in gen_server:init_it/6 line 352
